version: '3'
services:
  budgeting-app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - PORT=3000  # Internal port for the application
    volumes:
      - .:/usr/src/app
    command: npm start
