name = "budgeting-app"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./public"

routes = [
  { pattern = "budget.frootsnoops.com", custom_domain = true }
]

# Environment variables (optional)
# [vars]
# NODE_ENV = "production"
